USAGOV-1776-static-site-integrity: script gets three random static site backups and tests them

diff --git a/bin/cloudgov/test/static-site-integrity b/bin/cloudgov/test/static-site-integrity
--- a/bin/cloudgov/test/static-site-integrity
+++ b/bin/cloudgov/test/static-site-integrity
@@ -1,34 +1,40 @@
 #!/bin/bash
+echo "Testing static site integrity."
 
-RED='\033[0;31m'
-NC='\033[0m' # No Color
+echo "Getting s3 access."
+source bin/cloudgov/get-s3-access storage >/dev/null 2>&1
 
-echo "get s3 access"
-# source bin/cloudgov/get-s3-access storage >/dev/null 2>&1
-echo "get latest backup tag from s3.  this will take awhile."
-# DEPLOY_TAG=$(aws s3 ls --recursive $S3_BUCKET/web-backup/ | sort | tail -n 1 | awk '{split($4, array, "/"); print array[2]}')
-DEPLOY_TAG="USAGOV-1804.prod.10462.post-deploy" # temp for testing
-echo "DEPLOY_TAG: $DEPLOY_TAG"
-echo "downloading static site. also will take awhile"
-# aws s3 cp --only-show-errors s3://$S3_BUCKET/web-backup/$DEPLOY_TAG $DEPLOY_TAG --recursive
-count=$(find $DEPLOY_TAG -type f | wc -l)
-echo "File count: $count"
-echo "get three random html files for testing"
-for i in {1..3}; do
-  filepath=$(find $DEPLOY_TAG -type f -name "*.html" | shuf -n 1)
-  echo "Testing file $i: $filepath"
+echo "Getting three random backup tags from s3."
+DEPLOY_TAGS=$(aws s3 ls s3://"$S3_BUCKET"/web-backup/ | grep -E 'USAGOV-.*\.*-deploy/' | sed \$d | sort -R | tail -n 3)
 
-  tmp=$(mktemp)
-  tidy -qe "$filepath" &> "$tmp"
-  if [ $? -eq 0 ]; then
-    echo "Valid HTML!"
-  else
-    echo -e "\033[0;31mHTML is invalid, output:"
-    cat "$tmp"
-    echo -e "\033[0m"
-  fi
-  rm "$tmp"
+echo "$DEPLOY_TAGS" | while read -r DEPLOY_TAG_RAW ; do
+  DEPLOY_TAG=$(echo "$DEPLOY_TAG_RAW" | awk '{ print $2 }')
+  echo "Downloading static site: $DEPLOY_TAG"
+  aws s3 cp --only-show-errors s3://"$S3_BUCKET"/web-backup/"$DEPLOY_TAG" "$DEPLOY_TAG" --recursive
+
+  echo "Testing $DEPLOY_TAG."
+  count=$(find "$DEPLOY_TAG" -type f | wc -l)
+  echo "File count: $count."
+
+  size=$(du -hs "$DEPLOY_TAG")
+  echo "Directory size: $size."
+
+  echo "Getting three random html files for testing integrity testing with Tidy."
+  for i in {1..3}; do
+    filepath=$(find "$DEPLOY_TAG" -type f -name "*.html" | shuf -n 1)
+    echo "Testing file $i: $filepath"
+
+    tmp=$(mktemp)
+    tidy -qe "$filepath" &> "$tmp"
+    if [ $? -eq 0 ]; then
+      echo "Tidy says HTML is valid!"
+    else
+      echo -e "\033[0;31mHTML is invalid, output:"
+      cat "$tmp"
+      echo -e "\033[0m"
+    fi
+    rm "$tmp"
+  done
 
 done
-
-echo "done"
+echo "Automated testing complete. Do visual testing before deleting the backups."
