USAGOV-1056-store-image-digests: USAGOV-1056 - error handling

diff --git a/bin/deploy/fetch-image-digest-from-s3 b/bin/deploy/fetch-image-digest-from-s3
--- a/bin/deploy/fetch-image-digest-from-s3
+++ b/bin/deploy/fetch-image-digest-from-s3
@@ -21,11 +21,12 @@ else
     exit 1
 fi
 
+### This is too painful to do for this script...
 # just testing?
-if [ x$1 == x"--dryrun" ]; then
-  export echo=echo
-  shift
-fi
+#if [ x$1 == x"--dryrun" ]; then
+#  export echo=echo
+#  shift
+#fi
 
 APP_NAME=$1
 shift
@@ -63,10 +64,22 @@ echo "CCI_BUILD_ID  $CCI_BUILD_ID"
 echo "SPACE         $SPACE"
 echo "DOCKERUSER    $DOCKERUSER"
 echo "DOCKERREPO    $DOCKERREPO"
-echo "ECHO          $echo"
+#echo "ECHO          $echo"
+echo
 
-$echo cf target -s $SPACE
-$echo assertCurSpace $SPACE
-$echo . ./bin/cloudgov/get-s3-access key-value
-$echo aws s3 cp s3://${S3_BUCKET}/${DOCKERUSER}/${DOCKERREPO}/${APP_NAME}-${CCI_BUILD_ID} .
-$echo popspace
+cf target -s $SPACE &> /dev/null
+assertCurSpace $SPACE
+
+## The existsCFService test is needed because if, for some reason, the service does not exist
+## in $SPACE then get-s3-access will exit the current process, leaving us stuck in $SPACE rather than
+## politely failing and leaving us in the space we started from.
+if existsCFService key-value; then
+    $echo . ./bin/cloudgov/get-s3-access key-value
+    $echo aws s3 cp s3://${S3_BUCKET}/${DOCKERUSER}/${DOCKERREPO}/${APP_NAME}-${CCI_BUILD_ID} .
+    retval=$?
+else
+    retval=1
+fi
+
+popspace
+exit $retval
