USAGOV-908-snapshots-from-circleci: USAGOV-908 - utilities to query/modify the ssh allowed status for a cf space

diff --git a/bin/deploy/includes b/bin/deploy/includes
--- a/bin/deploy/includes
+++ b/bin/deploy/includes
@@ -202,3 +202,29 @@ function createSpaceAssertedBackupTag() {
 
   echo $BACKUP_TAG
 }
+
+function isSpaceSSHEnabled() {
+   sshSpace=$1
+   cf space-ssh-allowed $sshSpace | grep enabled &> /dev/null
+   return $?
+}
+
+function assertSpaceSSHEnabled() {
+  sshSpace=$1
+  if ! isSpaceSSHEnabled $sshSpace; then
+    echo "ERROR: SSH is not enabled for space: $sshSpace."
+    exit 1
+  fi
+}
+
+function enableSpaceSSH() {
+   sshSpace=$1
+   cf allow-space-ssh $sshSpace
+   return $?
+}
+
+function disableSpaceSSH() {
+   sshSpace=$1
+   cf disallow-space-ssh $sshSpace
+   return $?
+}
