USAGOV-1013-circleci-integration-automation: Increased error detection/handling

diff --git a/bin/deploy/try-tome-enable b/bin/deploy/try-tome-enable
--- a/bin/deploy/try-tome-enable
+++ b/bin/deploy/try-tome-enable
@@ -22,8 +22,31 @@ if ! isSpaceSSHEnabled $startspace; then
   needsDisabled=1
 fi
 
-echo "Running: /var/www/scripts/tome-disabled-toggle.sh 0"
-$echo cf ssh cms -c "/var/www/scripts/tome-disabled-toggle.sh 0"
-
 echo "Running: /var/www/scripts/toggle-maintenance-mode.sh 0"
 $echo cf ssh cms -c "/var/www/scripts/maintenance-mode-toggle.sh 0"
+retval=$?
+
+if [ $retval != 0 ]; then
+  echo
+  echo "Disabling Drupal's maintenance mode may have failed."
+  echo "Static Site Generation will therefore remain disabled."
+  echo "Please check this in the CMS, ASAP!"
+  echo
+else
+  echo "Running: /var/www/scripts/tome-disabled-toggle.sh 0"
+  $echo cf ssh cms -c "/var/www/scripts/tome-disabled-toggle.sh 0"
+  td_retval=$?
+  if [ $td_retval != 0 ]; then
+    echo
+    echo "Enabling Static Site Generation may have failed."
+    echo "Please check this the CMS, ASAP!"
+    echo
+    retval=$td_retval
+  fi
+fi
+
+if [ $needsDisabled != 0 ]; then
+   cf disallow-space-ssh $startspace
+fi
+
+exit $retval
