USAGOV-1069-ensure-backups-run-in-correct-space: remove printOrRun calls

diff --git a/bin/snapshot-backups/db-dump-to-snapshot b/bin/snapshot-backups/db-dump-to-snapshot
--- a/bin/snapshot-backups/db-dump-to-snapshot
+++ b/bin/snapshot-backups/db-dump-to-snapshot
@@ -35,20 +35,29 @@ TAG=$1
 SQLGZ=${TAG}.sql.gz
 SQLZIP=${TAG}.sql.zip
 
-$echo bin/snapshot-backups/db-dump-download $dryrun $TAG
+$echo bin/snapshot-backups/db-dump-download $dryrun $SPACE $TAG
 
 if [ -f $SQLGZ ]; then
    if [[ -n $(zcat -f ${SQLGZ} | head | grep 'SET NAMES utf8mb4') ]]; then
       if [[ -n $(zcat -f ${SQLGZ} | tail | grep 'Dump completed on' ) ]]; then
-         $echo bin/snapshot-backups/db-dump-push-to-snapshot $dryrun $TAG
-         echo snapshotted $TAG
-         echo "cleaning local files:"
-         ls -l ${TAG}*
-         rm -f ${TAG}*
-         echo "checking for leftovers (none should be found):"
-         ls -l ${TAG}*; true
+        $echo bin/snapshot-backups/db-dump-push-to-snapshot $dryrun $SPACE $TAG
+        if [ $? != 0 ]; then
+          echo "Could not push snapshot '$TAG' to $SPACE s3"
+          exit 1
+        else
+          echo snapshotted $TAG
+          echo "Attempting to clear local files:"
+          rm -f ${TAG}*
+          ls -l ${TAG}* &> /dev/null
+          if [ "$?" != "0" ]; then
+             echo "Error: Could not delete temporary files:"
+             ls -l ${TAG}*
+             exit 1
+          fi
+        fi
+        exit 0
       else
-         echo "SQL dump does not appear to be valid (no 'Dump completed on' string found on tail of file)"
+        echo "SQL dump does not appear to be valid (no 'Dump completed on' string found on tail of file)"
       fi
    else
       echo "SQL dump does not appear to be valid (no 'SET NAMES utf8mb4' string found on head of file)"
