USAGOV-1069-ensure-backups-run-in-correct-space: USAGOV-1069 - add CF space checking to the download and list scripts

diff --git a/bin/snapshot-backups/db-snapshot-download b/bin/snapshot-backups/db-snapshot-download
--- a/bin/snapshot-backups/db-snapshot-download
+++ b/bin/snapshot-backups/db-snapshot-download
@@ -12,12 +12,23 @@ fi
 if [ -f ./env.local ]; then
   . ./env.local
 fi
+if [ -f $SCRIPT_DIR/../deploy/includes ]; then
+  . $SCRIPT_DIR/../deploy/includes
+else
+   echo Cannot find $SCRIPT_DIR/../deploy/includes
+   exit 1
+fi
 
 # just testing?
-if [ x$1 == x"--dryrun" ]; then
+if [ x$1 = x"--dryrun" ]; then
   export echo=echo
   shift
 fi
+
+SPACE=${1:-please-provide-space-name-as-first-argument}
+SPACE=${SPACE,,}
+assertCurSpace $SPACE
+shift
 
 DEPLOY_TAG=${1}
 
@@ -27,12 +38,11 @@ if [ -z "$DEPLOY_TAG" ]; then
   exit 1
 fi
 
-#SPACE=$( cf target | grep space: | awk '{ print $2 }')
 #PREFIX=usagov-${DEPLOY_TAG}-${SPACE}
 GZIP_FILE=${DEPLOY_TAG}.sql.gz
 
-$echo source bin/cloudgov/get-s3-access storage >/dev/null 2>&1
+source bin/cloudgov/get-s3-access storage >/dev/null 2>&1
 
 echo "Attempting to download $GZIP_FILE from s3. This could take awhile."
-echo  aws s3 cp --only-show-errors s3://$S3_BUCKET/db-backup/$GZIP_FILE $GZIP_FILE
-$echo aws s3 cp --only-show-errors s3://$S3_BUCKET/db-backup/$GZIP_FILE $GZIP_FILE
+#echo  aws s3 cp --only-show-errors s3://$S3_BUCKET/db-backup/$GZIP_FILE $GZIP_FILE
+printOrRun "$echo" "aws s3 cp --only-show-errors s3://$S3_BUCKET/db-backup/$GZIP_FILE $GZIP_FILE"
diff --git a/bin/snapshot-backups/public-snapshot-download b/bin/snapshot-backups/public-snapshot-download
--- a/bin/snapshot-backups/public-snapshot-download
+++ b/bin/snapshot-backups/public-snapshot-download
@@ -20,13 +20,23 @@ else
    echo Cannot find ${PWD}/bin/snapshot-backups/snapshot-include
    exit 1
 fi
-
+if [ -f $SCRIPT_DIR/../deploy/includes ]; then
+  . $SCRIPT_DIR/../deploy/includes
+else
+   echo Cannot find $SCRIPT_DIR/../deploy/includes
+   exit 1
+fi
 
 # just testing?
-if [ x$1 == x"--dryrun" ]; then
+if [ x$1 = x"--dryrun" ]; then
   export echo=echo
   shift
 fi
+
+SPACE=${1:-please-provide-space-name-as-first-argument}
+SPACE=${SPACE,,}
+assertCurSpace $SPACE
+shift
 
 DEPLOY_TAG=${1}
 shift
@@ -74,12 +84,10 @@ else
 fi
 
 echo "Downloading files from s3 to local directory './${SOURCE_DIR}'. This could take awhile."
-echo aws s3 cp --only-show-errors s3://$S3_BUCKET/$BUCKET_BACKUP_FOLDER/$DEPLOY_TAG $SOURCE_DIR --recursive
-$echo aws s3 cp --only-show-errors s3://$S3_BUCKET/$BUCKET_BACKUP_FOLDER/$DEPLOY_TAG $SOURCE_DIR --recursive
+printOrRun "$echo" "aws s3 cp --only-show-errors s3://$S3_BUCKET/$BUCKET_BACKUP_FOLDER/$DEPLOY_TAG $SOURCE_DIR --recursive"
 
 echo "Creating zip file $ZIP_FILE"
-echo zip -rq ${ZIP_FILE} ${SOURCE_DIR}
-$echo zip -rq ${ZIP_FILE} ${SOURCE_DIR}
+printOrRun "$echo" "zip -rq ${ZIP_FILE} ${SOURCE_DIR}"
 success=$?
 
 if [ "$success" != "0" ]; then
@@ -87,7 +95,7 @@ if [ "$success" != "0" ]; then
   exit 1
 fi
 
-$echo rm -rf $SOURCE_DIR
+printOrRun "$echo" "rm -rf $SOURCE_DIR"
 echo "Done."
 
 exit 0
