USAGOV-1069-ensure-backups-run-in-correct-space: Restore instructions, snap zip checks

diff --git a/bin/snapshot-backups/local-snapshot-deploy b/bin/snapshot-backups/local-snapshot-deploy
--- a/bin/snapshot-backups/local-snapshot-deploy
+++ b/bin/snapshot-backups/local-snapshot-deploy
@@ -39,6 +39,23 @@ if [ -z "$SNAPSHOT_TAG" ]; then
 fi
 shift
 
+DB_SNAPSHOT_ZIP=${SNAPSHOT_TAG}.sql.gz
+PUBLIC_SNAPSHOT_ZIP=${SNAPSHOT_TAG}.public.zip
+SITE_SNAPSHOT_ZIP=${SNAPSHOT_TAG}.zip
+
+if [ x$echo = x ]; then
+  if [ ! -f $DB_SNAPSHOT_ZIP -o ! -f $SITE_SNAPSHOT_ZIP -o ! -f $PUBLIC_SNAPSHOT_ZIP ]; then
+    echo "One or more of the following snapshot files is missing from the current directory:"
+    echo
+    echo "    DB_SNAPSHOT_ZIP     $DB_SNAPSHOT_ZIP"
+    echo "    PUBLIC_SNAPSHOT_ZIP $PUBLIC_SNAPSHOT_ZIP"
+    echo "    SITE_SNAPSHOT_ZIP   $SITE_SNAPSHOT_ZIP"
+    echo
+    echo "Please read bin/snapshot-backups/README-DR.md for details on downloading these files from storage"
+    echo
+    exit 1
+  fi
+fi
 
 RETVAL=0
 if [ x$echo = x ]; then
@@ -51,11 +68,11 @@ fi
 
 if [ "$RETVAL" = "0" ]; then
   echo  $SCRIPT_DIR/db-dump-deploy         $dryrun $SPACE $SNAPSHOT_TAG
-        $SCRIPT_DIR/db-dump-deploy         $dryrun $SPACE $SNAPSHOT_TAG
+  $echo $SCRIPT_DIR/db-dump-deploy         $dryrun $SPACE $SNAPSHOT_TAG
   echo  $SCRIPT_DIR/site-snapshot-deploy   $dryrun $SPACE $SNAPSHOT_TAG
-        $SCRIPT_DIR/site-snapshot-deploy   $dryrun $SPACE $SNAPSHOT_TAG
+  $echo $SCRIPT_DIR/site-snapshot-deploy   $dryrun $SPACE $SNAPSHOT_TAG
   echo  $SCRIPT_DIR/public-snapshot-deploy $dryrun $SPACE $SNAPSHOT_TAG
-        $SCRIPT_DIR/public-snapshot-deploy $dryrun $SPACE $SNAPSHOT_TAG
+  $echo $SCRIPT_DIR/public-snapshot-deploy $dryrun $SPACE $SNAPSHOT_TAG
 
   echo
   echo "***** Read Me *****"
diff --git a/bin/snapshot-backups/site-folder-push-to-snapshot b/bin/snapshot-backups/site-folder-push-to-snapshot
--- a/bin/snapshot-backups/site-folder-push-to-snapshot
+++ b/bin/snapshot-backups/site-folder-push-to-snapshot
@@ -38,6 +38,7 @@ if [ -z "$SOURCE_DIR" ]; then
   exit 1
 fi
 
+CLEANUP_REQUIRED=0
 if [ x"$DEPLOY_TAG" != x ]; then
   # locate a local directory that contains a build of the static site
   # do some sanity checking on the directory (steal from tome-sync)
@@ -45,8 +46,21 @@ if [ x"$DEPLOY_TAG" != x ]; then
     if [ -d "$SOURCE_DIR" ]; then
       echo "Found source directory: $SOURCE_DIR"
     else
-      echo "ERROR: Source directory not found: $SOURCE_DIR"
-      exit 1
+      if [ -f $ZIP_FILE ]; then
+        CLEANUP_REQUIRED=1
+        unzip $ZIP_FILE
+        if [ $? != 0 ]; then
+          echo "Error unzipping $ZIP_FILE"
+          exit 1
+        fi
+        if [ ! -d "$SOURCE_DIR" ]; then
+          echo "ERROR: Zip file ($ZIP_FILE) was unpacked, but seems not to have produced a valid source directory ($SOURCE_DIR)."
+          exit 1
+        fi
+      else
+        echo "ERROR: Source directory ($SOURCE_DIR) or zip file ($ZIP_FILE) not found"
+        exit 1
+      fi
     fi
   fi
 else
@@ -72,4 +86,12 @@ fi
 source bin/cloudgov/get-s3-access storage >/dev/null 2>&1
 
 # upload that static site directory to a location within an s3 bucket represented by the tag
-printOrRun "$echo" "aws s3 cp --only-show-errors $SOURCE_DIR s3://$S3_BUCKET/web-backup/$DEPLOY_TAG/ --recursive"
+echo  aws s3 cp --only-show-errors $SOURCE_DIR s3://$S3_BUCKET/web-backup/$DEPLOY_TAG/ --recursive
+$echo aws s3 cp --only-show-errors $SOURCE_DIR s3://$S3_BUCKET/web-backup/$DEPLOY_TAG/ --recursive
+retval=$?
+
+if [ $CLEANUP_REQUIRED = 1 ]; then
+  rm -rf $SOURCE_DIR
+fi
+
+exit $retval
