USAGOV-1069-ensure-backups-run-in-correct-space: USAGOV-1069 - add CF space assertion to snapshot scripts

diff --git a/bin/snapshot-backups/site-folder-push-to-snapshot b/bin/snapshot-backups/site-folder-push-to-snapshot
--- a/bin/snapshot-backups/site-folder-push-to-snapshot
+++ b/bin/snapshot-backups/site-folder-push-to-snapshot
@@ -12,12 +12,23 @@ fi
 if [ -f ./env.local ]; then
   . ./env.local
 fi
+if [ -f $SCRIPT_DIR/../deploy/includes ]; then
+  . $SCRIPT_DIR/../deploy/includes
+else
+   echo Cannot find $SCRIPT_DIR/../deploy/includes
+   exit 1
+fi
 
 # just testing?
-if [ x$1 == x"--dryrun" ]; then
+if [ x$1 = x"--dryrun" ]; then
   export echo=echo
   shift
 fi
+
+SPACE=${1:-please-provide-space-name-as-first-argument}
+SPACE=${SPACE,,}
+assertCurSpace $SPACE
+shift
 
 DEPLOY_TAG=${1}
 SOURCE_DIR=$DEPLOY_TAG
@@ -43,8 +54,7 @@ else
    exit 1
 fi
 
-$echo source bin/cloudgov/get-s3-access storage >/dev/null 2>&1
+source bin/cloudgov/get-s3-access storage >/dev/null 2>&1
 
 # upload that static site directory to a location within an s3 bucket represented by the tag
-echo aws s3 cp --only-show-errors $SOURCE_DIR s3://$S3_BUCKET/web-backup/$DEPLOY_TAG/ --recursive
-$echo aws s3 cp --only-show-errors $SOURCE_DIR s3://$S3_BUCKET/web-backup/$DEPLOY_TAG/ --recursive
+printOrRun "$echo" "aws s3 cp --only-show-errors $SOURCE_DIR s3://$S3_BUCKET/web-backup/$DEPLOY_TAG/ --recursive"
