USAGOV-784-defacement-recovery: Additional verbosity and documentation

diff --git a/bin/snapshot-backups/stw b/bin/snapshot-backups/stw
--- a/bin/snapshot-backups/stw
+++ b/bin/snapshot-backups/stw
@@ -8,6 +8,8 @@ else
    exit 1
 fi
 
+export echo=echo
+
 SPACE=$1
 BRANCH=$2
 SUFFIX=$3
@@ -15,14 +17,26 @@ COMMAND=$4
 
 if [ x$SPACE != x -a x$BRANCH != x -a x$SUFFIX != x -a x$COMMAND != x ]; then
 
+   if [ ! -f $COMMAND -a ! -x $COMMAND ]; then
+      COMMAND=${SCRIPT_DIR}/${COMMAND}
+   fi
+
+   if [ ! -f $COMMAND -a ! -x $COMMAND ]; then
+      echo
+      echo ERROR: "$COMMAND" not found
+      exit 1
+   fi
+
    BACKUP_TAG=$(createAssertedBackupTag $SPACE $BRANCH $SUFFIX)
+   echo
    echo "Running '$COMMAND' with tag:  $BACKUP_TAG"
    echo
 
 else
+   echo
    echo "Usage: $0 <cf-space-name> <branch-name (use deployment ticket number)> <suffix (pre_deploy or post_deploy)> <script>"
    echo "       $0 dev USAGOV-787 pre_deploy"
    exit 1
 fi
 
-$echo $COMMAND $BACKUP_TAG
+$echo ${SCRIPT_DIR}/${COMMAND} $BACKUP_TAG
