USAGOV-2473-parallel-service-creation: Change version of mysql (8.0 was deprecated for CG).  Added error handling to service creation steps.

diff --git a/bin/cloudgov/deploy-cache-service b/bin/cloudgov/deploy-cache-service
--- a/bin/cloudgov/deploy-cache-service
+++ b/bin/cloudgov/deploy-cache-service
@@ -50,6 +50,15 @@ shift
   else
     echo  cf create-service aws-elasticache-redis redis-3node-large ${CACHE_SERVICE_NAME} -t "cache-service"
     $echo cf create-service aws-elasticache-redis redis-3node-large ${CACHE_SERVICE_NAME} -t "cache-service"
+    
+    retval=$?
+
+    if [ x$echo -ne x ]; then
+      if [ $retval -ne 0 ]; then
+        echo "ERROR: Could not create cache service (exit code: $retval)"
+        exit $retval
+      fi
+    fi
   fi
 
   # wait until the aws-elasticache-redis service is fully provisioned
diff --git a/bin/cloudgov/deploy-rds-service b/bin/cloudgov/deploy-rds-service
--- a/bin/cloudgov/deploy-rds-service
+++ b/bin/cloudgov/deploy-rds-service
@@ -41,17 +41,26 @@ shift
     if [ "$SPACE" = "dev" ] ; then
        RDS_PLAN=small-mysql
     else
-	RDS_PLAN=small-mysql-redundant
+       RDS_PLAN=small-mysql-redundant
     fi
-    
+
     echo cf create-service aws-rds \
       $RDS_PLAN \
       database \
-      -c '{"version": "8.0"}'
+      -c '{"version": "8.4"}'
     $echo cf create-service aws-rds \
       $RDS_PLAN \
       database \
-      -c '{"version": "8.0"}'
+      -c '{"version": "8.4"}'
+
+    retval=$?
+
+    if [ x$echo -ne x ]; then
+      if [ $retval -ne 0 ]; then
+        echo "ERROR: Could not create database service (exit code: $retval)"
+        exit $retval
+      fi
+    fi
   fi
 
   # wait until the db is fully provisioned
