USAGOV-2513-deploy-app-error-checking: Add dryrun option, more error handling and mandatory space argument to deploy-cms.  Encapsulate some cf functions to better handle dryrun and consolidate error handling.

diff --git a/bin/cloudgov/deploy-cms b/bin/cloudgov/deploy-cms
--- a/bin/cloudgov/deploy-cms
+++ b/bin/cloudgov/deploy-cms
@@ -12,18 +12,36 @@ SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
 if [ -f $SCRIPT_DIR/env.local ]; then
   . $SCRIPT_DIR/env.local
 fi
+INCLUDES_BASE=$SCRIPT_DIR/../deploy/includes
+if [ -f $INCLUDES_BASE ]; then
+  . $INCLUDES_BASE
+else
+   echo Cannot find $INCLUDES_BASE
+   exit 1
+fi
 if [ -f ./env.local ]; then
   . ./env.local
+fi
+
+# just testing?
+if [ x$1 = x"--dryrun" ]; then
+  echo=echo
+  dryrun=$1
+  shift
 fi
 
 DOCKERUSER=${DOCKERUSER:-gsatts}
 DOCKERREPO=${DOCKERREPO:-usagov-2021}
 
+APP_SPACE=${1:-please-provide-space-name-as-first-argument}
+APP_SPACE=$(echo "$APP_SPACE" | tr '[:upper:]' '[:lower:]')
+assertCurSpace $APP_SPACE
+shift
+
+APP_ORG=getOrg
+
 CTAG=${1:-latest}
 CDIGEST=${2:-}
-
-APP_SPACE=$( cf target | grep space: | awk '{ print $2 }')
-APP_ORG=$(   cf target | grep org:   | awk '{ print $2 }')
 
 EGRESS_SPACE='shared-egress'
 #if [ "$APP_SPACE" == "dev-dr" ]; then
@@ -33,35 +51,14 @@ EGRESS_SPACE='shared-egress'
 # The Image digest for this tag should be looked up from cloud.gov storage
 # Any tag with a stored Image digest should be referenced by hash instead of tag
 
-function appExists {  # appname
-  app=$1
-  if [ -z "$app" ]; then
-    echo "ERROR: app name is required"
-    exit 1
-  fi
-  echo cf app $app > /dev/null 2>&1
-  cf app $app > /dev/null 2>&1
-  return $?
-}
-
-function serviceExists {  # service name
-  service=$1
-  if [ -z "$service" ]; then
-    echo "ERROR: service name is required"
-    exit 1
-  fi
-  echo cf service $service > /dev/null 2>&1
-  cf service $service > /dev/null 2>&1
-  return $?
-}
-
 function restartApp { #appname
   app=$1
   if [ -z "$app" ]; then
     echo "ERROR: appname is required"
     exit 1
   fi
-  cf restart $app --no-wait --strategy rolling
+  echo cf restart $app --no-wait --strategy rolling
+  $echo cf restart $app --no-wait --strategy rolling
 }
 
 function pushApp { #appname
@@ -83,17 +80,33 @@ function pushApp { #appname
   if [ -z "$CDIGEST" ]; then
     echo "Deploying ${DOCKERUSER}/${DOCKERREPO}:${app}-${CTAG}"
     if [ -z "$DOCKERHUB_ACCESS_TOKEN" ]; then
-      cf push $app $instances --docker-image ${DOCKERUSER}/${DOCKERREPO}:${app}-${CTAG} --strategy rolling
+      echo  cf push $app $instances --docker-image ${DOCKERUSER}/${DOCKERREPO}:${app}-${CTAG} --strategy rolling
+      $echo cf push $app $instances --docker-image ${DOCKERUSER}/${DOCKERREPO}:${app}-${CTAG} --strategy rolling
+      RETVAL=$?
     else
-      CF_DOCKER_PASSWORD=$DOCKERHUB_ACCESS_TOKEN cf push $app $instances --docker-image ${DOCKERUSER}/${DOCKERREPO}:${app}-${CTAG} --docker-username $DOCKERHUB_USERNAME --strategy rolling
+      export CF_DOCKER_PASSWORD=$DOCKERHUB_ACCESS_TOKEN
+      echo  cf push $app $instances --docker-image ${DOCKERUSER}/${DOCKERREPO}:${app}-${CTAG} --docker-username $DOCKERHUB_USERNAME --strategy rolling
+      $echo cf push $app $instances --docker-image ${DOCKERUSER}/${DOCKERREPO}:${app}-${CTAG} --docker-username $DOCKERHUB_USERNAME --strategy rolling
+      RETVAL=$?
+      unset CF_DOCKER_PASSWORD
     fi
   else
     echo "Deploying ${DOCKERUSER}/${DOCKERREPO} ${app}-${CTAG} via digest ${CDIGEST}"
     if [ -z "$DOCKERHUB_ACCESS_TOKEN" ]; then
-	    cf push $app $instances --docker-image ${DOCKERUSER}/${DOCKERREPO}${CDIGEST} --strategy rolling
+      echo  cf push $app $instances --docker-image ${DOCKERUSER}/${DOCKERREPO}${CDIGEST} --strategy rolling
+      $echo cf push $app $instances --docker-image ${DOCKERUSER}/${DOCKERREPO}${CDIGEST} --strategy rolling
+      RETVAL=$?
     else
-      CF_DOCKER_PASSWORD=$DOCKERHUB_ACCESS_TOKEN cf push $app $instances --docker-image ${DOCKERUSER}/${DOCKERREPO}${CDIGEST} --docker-username $DOCKERHUB_USERNAME --strategy rolling
+      export CF_DOCKER_PASSWORD=$DOCKERHUB_ACCESS_TOKEN
+      echo  cf push $app $instances --docker-image ${DOCKERUSER}/${DOCKERREPO}${CDIGEST} --docker-username $DOCKERHUB_USERNAME --strategy rolling
+      $echo cf push $app $instances --docker-image ${DOCKERUSER}/${DOCKERREPO}${CDIGEST} --docker-username $DOCKERHUB_USERNAME --strategy rolling
+      RETVAL=$?
+      unset CF_DOCKER_PASSWORD
     fi
+  fi
+  if [ $RETVAL -ne 0 ]; then
+    echo "ERROR: cf push failed ($RETVAL)"
+    exit $RETVAL
   fi
 }
 
@@ -104,19 +117,16 @@ function setupRoutes { #appname
     exit 1
   fi
 
-  cf create-route apps.internal --hostname cms-$APP_SPACE-usagov
-  cf map-route $app apps.internal --hostname cms-$APP_SPACE-usagov
-
+  createRoute apps.internal cms-$APP_SPACE-usagov
+  mapRoute $app apps.internal cms-$APP_SPACE-usagov
+  
   if [ "$APP_SPACE" == "prod" ]; then
-     cf create-route usa.gov --hostname cms
-     cf map-route $app usa.gov --hostname cms
-
+     createRoute usa.gov cms
+     mapRoute $app usa.gov cms
   else
-    cf create-route usa.gov --hostname cms-$APP_SPACE
-    cf map-route $app usa.gov --hostname cms-$APP_SPACE
-
+    createRoute usa.gov cms-$APP_SPACE
+    mapRoute $app usa.gov cms-$APP_SPACE
   fi
-
 }
 
 function setupEgress { #appname
@@ -125,28 +135,41 @@ function setupEgress { #appname
     echo "ERROR: appname is required"
     exit 1
   fi
-  $SCRIPT_DIR/setup-egress-for-apps $app --no-restart
+
+  if [ x$echo != x ]; then
+    echo DRYRUN=yes $SCRIPT_DIR/setup-egress-for-apps $app --no-restart
+    DRYRUN=yes $SCRIPT_DIR/setup-egress-for-apps $app --no-restart
+  else
+    echo $SCRIPT_DIR/setup-egress-for-apps $app --no-restart
+    $SCRIPT_DIR/setup-egress-for-apps $app --no-restart
+    RETVAL=$?
+    if [ $RETVAL -ne 0 ]; then
+      echo "ERROR: setup-egress-for-apps failed ($RETVAL)"
+      exit $RETVAL
+    fi
+  fi
 }
 
 function setUSPSCreds {
-  cf set-env cms USPS_USERID $USPS_USERID
-  cf set-env cms USPS_PASSWORD $USPS_PASSWORD
+  cfSetEnv cms USPS_API_ENV $USPS_API_ENV
+  cfSetEnv cms USPS_USERID $USPS_USERID
+  cfSetEnv cms USPS_PASSWORD $USPS_PASSWORD
 }
 
 function setCallCenterEWTBucket {
-  cf set-env cms CALL_CENTER_EWT_BUCKET $CALL_CENTER_EWT_BUCKET
+  cfSetEnv cms CALL_CENTER_EWT_BUCKET $CALL_CENTER_EWT_BUCKET
 }
 
-if appExists cms; then
+if existsCFApp cms; then
   setupRoutes cms
   setupEgress cms
   setUSPSCreds
   setCallCenterEWTBucket
-  if serviceExists "cache-service"; then
-      cf bind-service cms cache-service
+  if existsCFService "cache-service"; then
+      bindServiceToApp cms cache-service
   fi
-  if serviceExists "s3forAnalyticsReporter"; then
-      cf bind-service cms s3forAnalyticsReporter
+  if existsCFService "s3forAnalyticsReporter"; then
+      bindServiceToApp cms s3forAnalyticsReporter
   fi
   pushApp cms
 else
@@ -154,11 +177,11 @@ else
   pushApp cms
   setupRoutes cms
   setupEgress cms
-  if serviceExists "cache-service"; then
-      cf bind-service cms cache-service
+  if existsCFService "cache-service"; then
+      bindServiceToApp cms cache-service
   fi
-  if serviceExists "s3forAnalyticsReporter"; then
-      cf bind-service cms s3forAnalyticsReporter
+  if existsCFService "s3forAnalyticsReporter"; then
+      bindServiceToApp cms s3forAnalyticsReporter
   fi
   setUSPSCreds
   setCallCenterEWTBucket
diff --git a/bin/deploy/includes b/bin/deploy/includes
--- a/bin/deploy/includes
+++ b/bin/deploy/includes
@@ -336,3 +336,79 @@ function assertIsImageDigest() {
     fi
   done
 }
+
+function createRoute {
+  route=$1
+  host=$2
+  if [ -z "$route" -o -z "$host" ]; then
+    echo "ERROR: route and host are required for createRoute"
+    exit 1
+  fi
+  
+  echo cf create-route $route --hostname $host
+  $echo cf create-route $route --hostname $host
+  RETVAL=$?
+  if [ $RETVAL -ne 0 ]; then
+    echo "ERROR: cf create-route failed ($RETVAL)"
+    exit $RETVAL
+  fi
+}
+
+function mapRoute {
+  app=$1
+  route=$2
+  host=$3
+  if [ -z "$app" -o -z "$route" -o -z "$host" ]; then
+    echo "ERROR: app, route and host are required for mapRoute"
+    exit 1
+  fi
+  
+  echo cf map-route $app $route --hostname $host
+  $echo cf map-route $app $route --hostname $host
+  RETVAL=$?
+  if [ $RETVAL -ne 0 ]; then
+    echo "ERROR: cf map-route failed ($RETVAL)"
+    exit $RETVAL
+  fi
+}
+
+function bindServiceToApp {
+  app=$1
+  service=$2
+  assert=$3
+  if [ -z "$app" -o -z "$service" ]; then
+    echo "ERROR: app and service are required arguments for bindServiceToApp"
+    exit 1
+  fi
+
+  echo cf bind-service $app $service
+  $echo cf bind-service $app $service
+  RETVAL=$?
+  if [ x$assert = x ]; then
+    if [ $RETVAL -ne 0 ]; then
+      echo "ERROR: cf bind-service failed ($RETVAL)"
+      exit $RETVAL
+    fi
+  else
+    if [ $RETVAL -ne 0 ]; then
+      echo "NOTICE: cf bind-service $app $service failed ($RETVAL)"
+      return 0
+    fi
+  fi
+}
+
+function cfSetEnv {
+  app=$1
+  var=$2
+  val=$3
+  RETVAL=0
+  if [ -n "$var" ] && [ -n "$val" ] && [ -n "$app" ]; then
+    echo cf set-env $app $var $val
+    $echo cf set-env $app $var $val
+    RETVAL=$?
+  else
+    echo "NOTICE: cf set-env requires app, var and val to be set"
+    echo "Values are app: [$app], var: [$var], val: [$val]"
+  fi
+  return $RETVAL
+}
