USAGOV-2220-api-proxy-python: removed domain from proxy request and added it as required for keys

diff --git a/bin/cloudgov/deploy-api-proxy b/bin/cloudgov/deploy-api-proxy
--- a/bin/cloudgov/deploy-api-proxy
+++ b/bin/cloudgov/deploy-api-proxy
@@ -1,7 +1,7 @@
 #!/bin/bash
 set -e  # Exit on any error
 
-# this function is a convenient symantic wrapper around a one-liner
+# this function is a convenient semantic wrapper around a one-liner
 service_exists()
 {
   cf service "$1" >/dev/null 2>&1
@@ -53,6 +53,16 @@ fi
   fi
 }
 
+# Bind key storage service to the API Proxy
+echo "🔗 Binding Key Storage Service to API Proxy..."
+if cf bind-service api-proxy key-storage > /dev/null 2>&1; then
+  cf restart api-proxy
+  echo "✅ Key Storage Service bound successfully."
+else
+  echo "❌ Failed to bind Key Storage Service to API Proxy."
+  exit 1
+fi
+
 # Deploy API Proxy
 echo "🚀 Deploying API Proxy..."
 if cf push -f .buildpack/manifest-api-proxy.yml --no-route ; then
@@ -69,16 +79,6 @@ if cf map-route api-proxy apps.internal --hostname "${ORG}-${SPACE_NODOT}-api-pr
   echo "✅ Routes mapped successfully."
 else
   echo "❌ Failed to map routes to API Proxy."
-  exit 1
-fi
-
-# Bind key storage service to the API Proxy
-echo "🔗 Binding Key Storage Service to API Proxy..."
-if cf bind-service api-proxy key-storage > /dev/null 2>&1; then
-  cf restart api-proxy
-  echo "✅ Key Storage Service bound successfully."
-else
-  echo "❌ Failed to bind Key Storage Service to API Proxy."
   exit 1
 fi
 
