USAGOV-2530-deploy-cron: Add error handling to deploy-cron

diff --git a/bin/cloudgov/deploy-cron b/bin/cloudgov/deploy-cron
--- a/bin/cloudgov/deploy-cron
+++ b/bin/cloudgov/deploy-cron
@@ -1,85 +1,83 @@
 #!/usr/bin/env bash
-
+#
 # Deploy services and app for cron app.  Service creation should be idempotent.
+#
 
-# we might be running in circleci
-if [ -f /home/circleci/project/env.local ]; then
-  . /home/circleci/project/env.local
-fi
-# we might be running from a local dev machine
-SCRIPT_DIR="$(dirname "$0")"
-if [ -f $SCRIPT_DIR/env.local ]; then
-  . $SCRIPT_DIR/env.local
-fi
-if [ -f ./env.local ]; then
-  . ./env.local
-fi
-if [ -f $SCRIPT_DIR/../deploy/includes ]; then
-  . $SCRIPT_DIR/../deploy/includes
-else
-   echo Cannot find $SCRIPT_DIR/../deploy/includes
-   exit 1
-fi
+SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
+# Optional includes: we might be running in circleci, or a local dev machine
+for f in /home/circleci/project/env.local $SCRIPT_DIR/env.local ./env.local; do
+  if [ -f $f ]; then
+    . $f
+  fi
+done
+
+# Mandatory includes:
+for inc in $SCRIPT_DIR/../deploy/includes; do
+  if [ ! -f $inc ]; then
+    echo "Cannot find $inc"
+    exit 1
+  fi
+  . $inc
+done
 
 # just testing?
 if [ x$1 = x"--dryrun" ]; then
-  export echo=echo
+  echo=echo
+  dryrun=$1
   shift
 fi
-
-service_exists()
-{
-  cf service "$1" >/dev/null 2>&1
-}
-
-SPACE=${1:-please-provide-space-name-as-first-argument}
-SPACE=$(echo "$SPACE" | tr '[:upper:]' '[:lower:]')
-assertCurSpace $SPACE
-shift
-ORG=$(getOrg)
-CF_EGRESS_SPACE=${CF_EGRESS_SPACE:-shared-egress}
-CF_EGRESS_ORG=${CF_EGRESS_ORG:-$ORG}
-STAG=${1:-latest}
-SDIGEST=${2:-}
 
 DOCKERUSER=${DOCKERUSER:-gsatts}
 DOCKERREPO=${DOCKERREPO:-usagov-2021}
 
-export APPNAME="cron"
-export APPINSTANCES=1
+APP_SPACE=${1:-please-provide-space-name-as-first-argument}
+APP_SPACE=$(echo "$APP_SPACE" | tr '[:upper:]' '[:lower:]')
+assertCurSpace $APP_SPACE
+shift
+
+APP_ORG=getOrg
+
+export APP_NAME="cron"
+export APP_INSTANCES=1
+
+STAG=${1:-latest}
+SDIGEST=${2:-}
+
+CF_EGRESS_SPACE=${CF_EGRESS_SPACE:-shared-egress}
+CF_EGRESS_ORG=${CF_EGRESS_ORG:-$APP_ORG}
 
 if [ -z "$SDIGEST" ]; then
-  echo "AppSpec: ${DOCKERUSER}/${DOCKERREPO}:${APPNAME}-${STAG}"
-  APPSPEC="${DOCKERUSER}/${DOCKERREPO}:${APPNAME}-${STAG}"
+  echo "AppSpec: ${DOCKERUSER}/${DOCKERREPO}:${APP_NAME}-${STAG}"
+  APP_SPEC="${DOCKERUSER}/${DOCKERREPO}:${APP_NAME}-${STAG}"
 else
   echo "AppSpec: ${DOCKERUSER}/${DOCKERREPO}${SDIGEST}"
-  APPSPEC="${DOCKERUSER}/${DOCKERREPO}${SDIGEST}"
+  APP_SPEC="${DOCKERUSER}/${DOCKERREPO}${SDIGEST}"
 fi
 
 # launch the app
-echo "Deploying ${DOCKERUSER}/${DOCKERREPO}:${APPNAME}"
+echo "Deploying ${DOCKERUSER}/${DOCKERREPO}:${APP_NAME}"
 
-if existsCFService ${APPNAME}-service-account; then
-  echo "User service ${APPNAME}-service-account already exists - good!"
+if existsCFService ${APP_NAME}-service-account; then
+  echo "User service ${APP_NAME}-service-account already exists - good!"
 else
-  $SCRIPT_DIR/create-service-account $SPACE $APPNAME
+  $SCRIPT_DIR/create-service-account $APP_SPACE $APP_NAME
 fi
 
 if existsCFService cfevent-service-account; then
   echo "User service cfevent-service-account already exists - good!"
 else
-  $SCRIPT_DIR/create-service-account $SPACE cfevent
+  $SCRIPT_DIR/create-service-account $APP_SPACE cfevent
 fi
 
 if existsCFService callcenter-service-account; then
   echo "User service callcenter-service-account already exists - good!"
 else
-  $SCRIPT_DIR/create-service-account $SPACE callcenter
+  $SCRIPT_DIR/create-service-account $APP_SPACE callcenter
 fi
 
-STATE_STORAGE_SERVICE=${APPNAME}-state-storage
-EVENT_STORAGE_SERVICE=${APPNAME}-event-storage
-CALLWAIT_STORAGE_SERVICE=${APPNAME}-callwait-storage
+STATE_STORAGE_SERVICE=${APP_NAME}-state-storage
+EVENT_STORAGE_SERVICE=${APP_NAME}-event-storage
+CALLWAIT_STORAGE_SERVICE=${APP_NAME}-callwait-storage
 for storage_service in $STATE_STORAGE_SERVICE $EVENT_STORAGE_SERVICE $CALLWAIT_STORAGE_SERVICE; do
   echo "Configuring $storage_service"
   if existsCFService $storage_service &> /dev/null; then
@@ -105,25 +103,25 @@ function cf_push() {
   appspec=$1
   instances=${2:-1} ### Always spawn a single app instance unless told otherwise
   if [ -z "$DOCKERHUB_ACCESS_TOKEN" ]; then
-    cf push ${APPNAME} --docker-image ${appspec} --strategy rolling
+    cf push ${APP_NAME} --docker-image ${appspec} --strategy rolling
   else
-    CF_DOCKER_PASSWORD=$DOCKERHUB_ACCESS_TOKEN cf push ${APPNAME} --docker-image ${appspec} --docker-username $DOCKERHUB_USERNAME --strategy rolling
+    CF_DOCKER_PASSWORD=$DOCKERHUB_ACCESS_TOKEN cf push ${APP_NAME} --docker-image ${appspec} --docker-username $DOCKERHUB_USERNAME --strategy rolling
   fi
 }
 
-if existsCFApp ${APPNAME} ; then
-  $SCRIPT_DIR/setup-egress-for-apps ${APPNAME} --no-restart
-  retval=$?
-  if [ $retval != 0 ]; then
+if existsCFApp ${APP_NAME} ; then
+  $SCRIPT_DIR/setup-egress-for-apps ${APP_NAME} --no-restart
+  RETVAL=$?
+  if [ $RETVAL != 0 ]; then
     echo "ERROR: setup-egress-for-apps has failed.  Check output stream!"
     exit 1
   fi
-  cf_push $APPSPEC $APPINSTANCES
+  cf_push $APP_SPEC $APP_INSTANCES
 else
-  cf_push $APPSPEC $APPINSTANCES
-  $SCRIPT_DIR/setup-egress-for-apps ${APPNAME} --no-restart
-  retval=$?
-  if [ $retval != 0 ]; then ## Should retval be set above here?
+  cf_push $APP_SPEC $APP_INSTANCES
+  $SCRIPT_DIR/setup-egress-for-apps ${APP_NAME} --no-restart
+  RETVAL=$?
+  if [ $RETVAL != 0 ]; then ## Should RETVAL be set above here?
     echo "ERROR: setup-egress-for-apps has failed.  Check output stream!"
     exit 1
   fi
@@ -131,38 +129,78 @@ fi
 
 ### Setting up network policy so that cron app can talk to cms directly
 cf add-network-policy cron cms --protocol tcp --port 80
+RETVAL=$?
+if [ $RETVAL != 0 ]; then
+  echo "ERROR: cannot add network policy from cron to cms"
+  exit 1
+fi
 
 ### These are set for some reason - unset them at deployment
-cf unset-env $APPNAME HTTP_PROXY
-cf unset-env $APPNAME HTTPS_PROXY
-cf unset-env $APPNAME http_proxy
-cf unset-env $APPNAME https_proxy
+cfUnSetEnv $APP_NAME HTTP_PROXY
+cfUnSetEnv $APP_NAME HTTPS_PROXY
+cfUnSetEnv $APP_NAME http_proxy
+cfUnSetEnv $APP_NAME https_proxy
 
 ### Call center env (should we move this to a user-provided credentials service?)
-cf set-env $APPNAME CALL_CENTER_CLIENT_ID $CALL_CENTER_CLIENT_ID
-cf set-env $APPNAME CALL_CENTER_CLIENT_SECRET $CALL_CENTER_CLIENT_SECRET
-cf set-env $APPNAME CALL_CENTER_ENVIRONMENT $CALL_CENTER_ENVIRONMENT
-cf set-env $APPNAME CALL_CENTER_EN_QUEUE_ID $CALL_CENTER_EN_QUEUE_ID
-cf set-env $APPNAME CALL_CENTER_SP_QUEUE_ID $CALL_CENTER_SP_QUEUE_ID
+cfSetEnv $APP_NAME CALL_CENTER_CLIENT_ID $CALL_CENTER_CLIENT_ID
+cfSetEnv $APP_NAME CALL_CENTER_CLIENT_SECRET $CALL_CENTER_CLIENT_SECRET
+cfSetEnv $APP_NAME CALL_CENTER_ENVIRONMENT $CALL_CENTER_ENVIRONMENT
+cfSetEnv $APP_NAME CALL_CENTER_EN_QUEUE_ID $CALL_CENTER_EN_QUEUE_ID
+cfSetEnv $APP_NAME CALL_CENTER_SP_QUEUE_ID $CALL_CENTER_SP_QUEUE_ID
 
 ### Syncing lightweight cron key
 echo "Updating lightweight cron key"
-if service_exists "secrets" ; then
-  echo "secrets already created: updating"
-  SECRETS=$(cf curl /v3/service_instances/$(cf service secrets --guid)/credentials)
+if existsCFService "secrets" ; then
+  echo "secrets already created: updating for cron"
+  SGUID=$(cf service secrets --guid)
+  RETVAL=$?
+  if [ $RETVAL != 0 -o -z "$SGUID" ]; then
+    echo "ERROR: cannot get guid for the service: secrets"
+    exit 1
+  fi
+  SECRETS=$(cf curl /v3/service_instances/$SGUID/credentials)
+  RETVAL=$?
+  if [ $RETVAL != 0 -o -z "$SECRETS" ]; then
+    echo "ERROR: cannot get credentials for the service: secrets"
+    exit 1
+  fi
   CRON_KEY=$(echo $SECRETS | jq -r '.CRON_KEY')
+  if [ -z "$CRON_KEY" -o "$CRON_KEY" = "null" ]; then
+    echo "ERROR: cannot find CRON_KEY in the output from secrets service"
+    exit 1
+  fi
+  echo "Got CRON_KEY from secrets service"  
 
-  if service_exists "cron-secrets" ; then
+  if existsCFService "cron-secrets" ; then
     yes '' | cf update-user-provided-service cron-secrets -p "{\"CRON_KEY\": \"$CRON_KEY\"}"
   else
     cf create-user-provided-service cron-secrets -p "{\"CRON_KEY\": \"$CRON_KEY\"}"
   fi
+  RETVAL=$?
+  if [ $RETVAL != 0 ]; then
+    echo "ERROR: cannot create or update the user-provided service: cron-secrets"
+    exit 1
+  fi
+else
+  echo "ERROR: cannot find the service: secrets.  Are you sure your environment is complete?"
+  exit 1
 fi
 
 # Enable call center / cfevents  scripts on prod only. (We can manually update this in dev, etc. for testing)
-if [ $SPACE = "prod" ]; then
-    cf set-env $APPNAME CALL_CENTER_RUN "true"
-    cf set-env $APPNAME CFEVENT_RUN "true"
+if [ $APP_SPACE = "prod" ]; then
+    cfSetEnv $APP_NAME CALL_CENTER_RUN "true"
+    RETVAL=$?
+    cfSetEnv $APP_NAME CFEVENT_RUN "true"
+    RETVAL2=$?
+    if [ $RETVAL != 0 -o $RETVAL2 != 0 ]; then
+      echo "ERROR: cannot set cf env vars for call center run, or cfevent run"
+      exit 1
+    fi
 fi
 
-cf restage $APPNAME --strategy rolling
+cf restage $APP_NAME --strategy rolling
+RETVAL=$?
+if [ $RETVAL != 0 ]; then
+  echo "ERROR: restaging cron app failed"
+  exit 1
+fi
